"""Seed the MuseForge knowledge base with synthetic, cross-linked knowledge.

This is *synthetic* seed content authored for MuseForge — not copied from any third-party
repository. It demonstrates the knowledge model and powers the six demos. Attribution fields
point at the repositories that *inspired* each abstraction (as public facts), never at copied
prompt text.

Run from the repo root:  python scripts/seed_data.py
"""

from __future__ import annotations

from museforge.knowledge.models import (
    Case,
    ModelKnowledge,
    Prompt,
    PromptDna,
    Recipe,
    Source,
    SourceType,
    Style,
    Technique,
    VisualPattern,
)
from museforge.knowledge.store import KnowledgeStore

# --------------------------------------------------------------------------- sources

SOURCES = [
    Source(id="awesome-gpt4o-images", name="jamez-bondos/awesome-gpt4o-images",
           url="https://github.com/jamez-bondos/awesome-gpt4o-images", license="CC BY 4.0",
           redistribution_status="allowed", attribution_requirements="Attribute author + source.",
           description="Curated GPT-4o + gpt-image-1 cases, bilingual, per-case attribution."),
    Source(id="awesome-nano-banana-pro-prompts", name="YouMind-OpenLab/awesome-nano-banana-pro-prompts",
           url="https://github.com/YouMind-OpenLab/awesome-nano-banana-pro-prompts", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="10,000+ Nano Banana Pro prompts, 16 languages, CMS-backed."),
    Source(id="awesome-gpt-image-2", name="YouMind-OpenLab/awesome-gpt-image-2",
           url="https://github.com/YouMind-OpenLab/awesome-gpt-image-2", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="2,000+ GPT Image 2 prompts, 16 languages."),
    Source(id="freestylefly-awesome-gpt-image-2", name="freestylefly/awesome-gpt-image-2",
           url="https://github.com/freestylefly/awesome-gpt-image-2", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="Prompt as Code: 530+ reverse-engineered cases, atomic schema, 20+ templates."),
    Source(id="awesome-gpt-image-2-api", name="EvoLinkAI/awesome-gpt-image-2-API-and-Prompts",
           url="https://github.com/EvoLinkAI/awesome-gpt-image-2-API-and-Prompts", license="CC0-1.0",
           redistribution_status="allowed", attribution_requirements="None (public domain).",
           description="GPT Image 2 API + prompts, cases/data/scripts separation."),
    Source(id="gpt-image2-skill", name="wuyoscar/GPT-Image2-Skill",
           url="https://github.com/wuyoscar/GPT-Image2-Skill", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="GPT Image 2 gallery + agent skill + CLI, JSON-style prompts."),
    Source(id="awesome-nanobanana-pro", name="ZeroLu/awesome-nanobanana-pro",
           url="https://github.com/ZeroLu/awesome-nanobanana-pro", license="CC BY 4.0",
           redistribution_status="allowed", attribution_requirements="Attribute author + source.",
           description="Curated Nano Banana Pro prompts with [VARIABLE] templates."),
    Source(id="awesome-nano-banana-images", name="PicoTrex/Awesome-Nano-Banana-images",
           url="https://github.com/PicoTrex/Awesome-Nano-Banana-images", license="CC BY 4.0",
           redistribution_status="allowed", attribution_requirements="Attribute author + source.",
           description="Nano Banana image-editing workflows (input -> output)."),
    Source(id="ai-visual-prompt-cookbook", name="VigoZhao/AI-Visual-Prompt-Cookbook",
           url="https://github.com/VigoZhao/AI-Visual-Prompt-Cookbook", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="118+ JSON style packs: copy one JSON, get a style."),
    Source(id="awesome-gpt4o-image-prompts", name="ImgEdify/Awesome-GPT4o-Image-Prompts",
           url="https://github.com/ImgEdify/Awesome-GPT4o-Image-Prompts", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="Bilingual GPT-4o prompt dictionary (Chinese exemplars)."),
    Source(id="ai-image-prompt-cookbook", name="gpt-img-2/ai-image-prompt-cookbook",
           url="https://github.com/gpt-img-2/ai-image-prompt-cookbook", license="unclear",
           redistribution_status="restricted", attribution_requirements="Do not copy prompt text.",
           description="Chinese e-commerce / Xiaohongshu / ad-poster cookbook."),
    Source(id="rednote-director-skill", name="mythkiven/rednote-director-skill",
           url="https://github.com/mythkiven/rednote-director-skill", license="unclear",
           redistribution_status="restricted", attribution_requirements="Do not copy prompt text.",
           description="Xiaohongshu visual-director agent skill."),
    Source(id="awesome-seedream-4.5", name="YouMind-OpenLab/awesome-seedream-4.5",
           url="https://github.com/YouMind-OpenLab/awesome-seedream-4.5", license="MIT",
           redistribution_status="allowed", attribution_requirements="MIT notice.",
           description="100+ Seedream 4.5 prompts, multilingual."),
    Source(id="gpt-image-2-gallery", name="ChaosRealmsAI/gpt-image-2-gallery",
           url="https://github.com/ChaosRealmsAI/gpt-image-2-gallery", license="MIT + CC BY 4.0",
           redistribution_status="allowed", attribution_requirements="Attribute where CC BY applies.",
           description="3,800+ GPT Image 2 works across 445 themes."),
    Source(id="nano-banana-json-schema", name="alexewerlof/nano-banana-json-schema",
           url="https://gist.github.com/alexewerlof/1d13401a7647339469141dc2960e66a9", license="unclear",
           redistribution_status="restricted", attribution_requirements="Do not copy prompt text.",
           description="Typed JSON schema for Nano Banana prompts (meta/subject/scene)."),
]

# --------------------------------------------------------------------------- models

MODELS = [
    ModelKnowledge(
        id="gpt-image", name="GPT Image", family="gpt-image", provider="OpenAI",
        capabilities=["text-to-image", "image editing", "text rendering"],
        strengths=["strong text rendering", "instruction following"],
        limitations=["consistency across long sessions can drift"],
        text_rendering="strong; put exact text in quotes and specify font style",
        consistency="good within a session; re-anchor with a consolidated prompt if it drifts",
        editing="conversational editing supported",
        prompt_style_notes="Structured, specific prompts work well; avoid vague adjectives.",
        source_type=SourceType.COMMUNITY_DERIVED,
        source_references=["awesome-gpt4o-images", "freestylefly-awesome-gpt-image-2"],
        tags=["openai", "text-rendering"]),
    ModelKnowledge(
        id="gpt-image-2", name="GPT Image 2", family="gpt-image", provider="OpenAI",
        capabilities=["text-to-image", "image editing", "pixel-perfect text", "cross-image consistency"],
        strengths=["pixel-perfect text rendering", "cross-image consistency", "commercial illustration"],
        limitations=["community-reported; no independent benchmark"],
        text_rendering="pixel-perfect; quote exact text and specify type style",
        consistency="strong cross-image consistency reported",
        editing="reference-based generation and editing",
        prompt_style_notes="JSON-style structured prompts are a practiced technique.",
        source_type=SourceType.REPOSITORY_DERIVED,
        source_references=["awesome-gpt-image-2", "freestylefly-awesome-gpt-image-2", "gpt-image2-skill"],
        tags=["openai", "text-rendering", "consistency"]),
    ModelKnowledge(
        id="nano-banana", name="Nano Banana", family="gemini", provider="Google",
        capabilities=["text-to-image", "image editing", "multi-image input"],
        strengths=["image editing", "multi-image workflows"],
        limitations=["community-reported; no independent benchmark"],
        text_rendering="good; quote exact text",
        consistency="good for character consistency workflows",
        editing="strong image-to-image editing",
        prompt_style_notes="Natural-language editing works well.",
        source_type=SourceType.COMMUNITY_DERIVED,
        source_references=["awesome-nano-banana-images"],
        tags=["google", "editing"]),
    ModelKnowledge(
        id="nano-banana-pro", name="Nano Banana Pro", family="gemini", provider="Google",
        capabilities=["text-to-image", "image editing", "4K output", "multilingual text"],
        strengths=["multilingual text accuracy", "subject consistency", "4K output"],
        limitations=["community-reported; no independent benchmark"],
        text_rendering="strong multilingual text; quote exact text",
        consistency="strong subject consistency reported",
        editing="strong editing and reference workflows",
        prompt_style_notes="Templated [VARIABLE] prompts are a practiced technique.",
        source_type=SourceType.REPOSITORY_DERIVED,
        source_references=["awesome-nano-banana-pro-prompts", "awesome-nanobanana-pro"],
        tags=["google", "text-rendering", "consistency"]),
    ModelKnowledge(
        id="seedream", name="Seedream", family="seedream", provider="ByteDance",
        capabilities=["text-to-image", "image editing", "precise typography", "character consistency"],
        strengths=["precise typography", "character consistency", "4K generation"],
        limitations=["community-reported; no independent benchmark"],
        text_rendering="precise typography reported",
        consistency="character consistency reported",
        editing="natural-language editing",
        prompt_style_notes="Structured prompts (subject/style/composition/typography) work well.",
        source_type=SourceType.COMMUNITY_DERIVED,
        source_references=["awesome-seedream-4.5"],
        tags=["bytedance", "text-rendering", "consistency"]),
]

# --------------------------------------------------------------------------- styles

STYLES = [
    Style(id="style-editorial-minimalism", name="editorial minimalism",
          aliases=["minimal", "极简", "editorial"],
          description="Clean, text-first, generous whitespace, restrained palette.",
          visual_characteristics=["generous whitespace", "restrained palette", "clear hierarchy"],
          composition_behavior="text-first with a single focal point",
          color_behavior="muted, 1-2 accent colors",
          lighting_behavior="even, soft",
          typography_behavior="strong sans-serif or serif headline, small supporting text",
          material_behavior="flat or subtle texture",
          texture_behavior="minimal grain",
          best_for=["recruitment posters", "editorial covers", "SaaS visuals"],
          avoid=["clutter", "high density", "many competing elements"],
          related_patterns=["pattern-editorial-text-first-poster", "pattern-minimal-saas-illustration"],
          related_techniques=["technique-whitespace", "technique-visual-hierarchy", "technique-text-rendering"],
          source_repositories=["freestylefly-awesome-gpt-image-2", "ai-visual-prompt-cookbook"],
          tags=["minimal", "editorial", "clean"]),
    Style(id="style-luxury-commercial", name="luxury commercial",
          aliases=["premium", "high-end", "奢华", "高端"],
          description="Dark, reflective, golden-hour, high-end product aesthetic.",
          visual_characteristics=["dark reflective surfaces", "golden-hour glow", "premium materials"],
          composition_behavior="centered hero with controlled negative space",
          color_behavior="deep tones + gold/amber accents",
          lighting_behavior="dramatic rim light, soft reflections",
          typography_behavior="elegant serif or refined sans",
          material_behavior="glass, metal, water",
          texture_behavior="smooth, reflective",
          best_for=["luxury product ads", "fintech cards", "premium branding"],
          avoid=["flat lighting", "busy backgrounds"],
          related_patterns=["pattern-centered-luxury-product", "pattern-breakout-product-hero"],
          related_techniques=["technique-lighting-control", "technique-color-grading", "technique-product-preservation"],
          source_repositories=["awesome-nanobanana-pro", "freestylefly-awesome-gpt-image-2"],
          tags=["luxury", "premium", "commercial"]),
    Style(id="style-premium-saas", name="premium SaaS",
          aliases=["saas", "software", "科技感"],
          description="Flat vector + device + brand color, minimal and modern.",
          visual_characteristics=["flat vector", "device composition", "brand color"],
          composition_behavior="device hero with minimal illustration",
          color_behavior="brand color + neutral background",
          lighting_behavior="soft, even",
          typography_behavior="clean sans-serif",
          material_behavior="flat, geometric",
          texture_behavior="none",
          best_for=["SaaS landing heroes", "app screenshots", "product marketing"],
          avoid=["photorealism", "clutter"],
          related_patterns=["pattern-minimal-saas-illustration", "pattern-hero-device-composition"],
          related_techniques=["technique-whitespace", "technique-visual-hierarchy"],
          source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
          tags=["saas", "flat", "tech"]),
    Style(id="style-cinematic-realism", name="cinematic realism",
          aliases=["photoreal", "写实", "cinematic"],
          description="85mm, shallow DOF, film grain, cinematic color grade.",
          visual_characteristics=["shallow depth of field", "film grain", "cinematic grade"],
          composition_behavior="subject-forward, rule of thirds",
          color_behavior="warm desaturated or teal-orange grade",
          lighting_behavior="motivated, high-contrast",
          typography_behavior="n/a (photography)",
          material_behavior="real textures",
          texture_behavior="natural skin texture, fabric detail",
          best_for=["portraits", "documentary", "cinematic scenes"],
          avoid=["flat lighting", "over-saturation"],
          related_patterns=["pattern-cinematic-character-portrait", "pattern-double-exposure-portrait"],
          related_techniques=["technique-camera-lens", "technique-lighting-control", "technique-color-grading"],
          source_repositories=["freestylefly-awesome-gpt-image-2"],
          tags=["cinematic", "photoreal", "portrait"]),
    Style(id="style-modern-chinese-editorial", name="modern Chinese editorial",
          aliases=["中文编辑", "国风", "chinese editorial"],
          description="Chinese typography, red/ink accents, structured editorial grid.",
          visual_characteristics=["Chinese typography", "red/ink accents", "editorial grid"],
          composition_behavior="structured grid with strong headline",
          color_behavior="red, ink black, paper white",
          lighting_behavior="even, editorial",
          typography_behavior="bold Chinese headline, refined supporting type",
          material_behavior="paper, ink",
          texture_behavior="subtle paper grain",
          best_for=["Chinese infographics", "Xiaohongshu covers", "editorial posters"],
          avoid=["western-only typography", "clutter"],
          related_patterns=["pattern-magazine-infographic", "pattern-editorial-text-first-poster"],
          related_techniques=["technique-text-rendering", "technique-visual-hierarchy"],
          source_repositories=["ai-image-prompt-cookbook", "rednote-director-skill"],
          tags=["chinese", "editorial", "infographic"]),
    Style(id="style-flat-vector", name="flat vector",
          aliases=["flat", "矢量", "扁平"],
          description="Minimal, geometric, brand-friendly flat illustration.",
          visual_characteristics=["flat shapes", "geometric", "no gradients"],
          composition_behavior="simple, balanced",
          color_behavior="2-4 flat colors",
          lighting_behavior="none (flat)",
          typography_behavior="clean sans-serif",
          material_behavior="flat",
          texture_behavior="none",
          best_for=["SaaS illustrations", "icons", "explainers"],
          avoid=["photorealism", "complex gradients"],
          related_patterns=["pattern-minimal-saas-illustration"],
          related_techniques=["technique-whitespace"],
          source_repositories=["gpt-image2-skill"],
          tags=["flat", "vector", "minimal"]),
    Style(id="style-retro-print", name="retro print",
          aliases=["retro", "vintage", "复古"],
          description="Halftone, grain, vintage palette, print texture.",
          visual_characteristics=["halftone", "grain", "vintage palette"],
          composition_behavior="poster-like, bold",
          color_behavior="muted vintage tones",
          lighting_behavior="flat print lighting",
          typography_behavior="bold display type",
          material_behavior="paper, ink",
          texture_behavior="halftone, grain",
          best_for=["posters", "editorial", "brand campaigns"],
          avoid=["photorealism"],
          related_patterns=["pattern-editorial-text-first-poster"],
          related_techniques=["technique-color-grading"],
          source_repositories=["freestylefly-awesome-gpt-image-2"],
          tags=["retro", "print", "poster"]),
    Style(id="style-3d-commercial", name="3D commercial",
          aliases=["3d", "render", "三维"],
          description="Product render, studio lighting, clean 3D.",
          visual_characteristics=["3D render", "studio lighting", "clean surfaces"],
          composition_behavior="product hero, three-quarter angle",
          color_behavior="true product colors",
          lighting_behavior="soft studio, diffused",
          typography_behavior="clean sans-serif",
          material_behavior="matte paperboard, glass, metal",
          texture_behavior="smooth, realistic",
          best_for=["product renders", "packaging", "e-commerce"],
          avoid=["flat lighting", "no shadows"],
          related_patterns=["pattern-floating-3d-product", "pattern-breakout-product-hero"],
          related_techniques=["technique-product-preservation", "technique-lighting-control"],
          source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
          tags=["3d", "render", "product"]),
]

# --------------------------------------------------------------------------- techniques

TECHNIQUES = [
    Technique(id="technique-text-rendering", name="text rendering", category="Typography",
              description="Put exact text in quotes and specify font style for accurate text.",
              problem_it_solves="Models garble or misspell text in images.",
              pattern="\"EXACT TEXT\" in [font style]",
              implementation_guidance="Quote every string; specify serif/sans/handwritten; keep text short.",
              when_to_use=["posters", "infographics", "ads with copy"],
              when_not_to_use=["pure photography without text"],
              good_examples=["\"MIDNIGHT REVERIE\" in bold art deco typography"],
              bad_examples=["some cool text on the poster"],
              related_patterns=["pattern-editorial-text-first-poster", "pattern-magazine-infographic"],
              related_recipes=["recipe-editorial-poster", "recipe-infographic"],
              related_styles=["style-editorial-minimalism", "style-modern-chinese-editorial"],
              source_repositories=["freestylefly-awesome-gpt-image-2", "gpt-image2-skill"],
              confidence=0.9, tags=["text", "typography"]),
    Technique(id="technique-product-preservation", name="product preservation", category="Product Preservation",
              description="Preserve critical product geometry and branding.",
              problem_it_solves="Models distort or redesign the product.",
              pattern="preserve [product] geometry; keep [brand] exact",
              implementation_guidance="Name the product, its shape, label, and colors; forbid redesign.",
              when_to_use=["product ads", "packaging", "e-commerce"],
              when_not_to_use=["abstract art"],
              good_examples=["assemble the dieline into a flawless 3D box with accurate panels"],
              bad_examples=["make a cool bottle"],
              related_patterns=["pattern-breakout-product-hero", "pattern-floating-3d-product"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-3d-commercial", "style-luxury-commercial"],
              source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
              confidence=0.9, tags=["product", "brand"]),
    Technique(id="technique-brand-preservation", name="brand preservation", category="Brand Preservation",
              description="Protect branding: exact name, logo, and brand colors.",
              problem_it_solves="Models alter or invent brand elements.",
              pattern="protect branding; exact [brand] name and logo",
              implementation_guidance="State the brand name in quotes; specify logo placement and colors.",
              when_to_use=["branded ads", "campaigns"],
              when_not_to_use=["unbranded concepts"],
              good_examples=["the box front reads \"AURAE / COLD-BREW MATCHA\""],
              bad_examples=["a nice logo"],
              related_patterns=["pattern-breakout-product-hero"],
              related_recipes=["recipe-product-hero-ad", "recipe-fintech-card-ad"],
              related_styles=["style-luxury-commercial"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["brand", "logo"]),
    Technique(id="technique-reference-image", name="reference image", category="Reference Image",
              description="Use an uploaded image as a reference for identity or structure.",
              problem_it_solves="Models can't match a specific face/object without a reference.",
              pattern="use the uploaded [face/object] 100% as reference",
              implementation_guidance="State what to preserve and what to change.",
              when_to_use=["character restyle", "product from photo", "editing"],
              when_not_to_use=["pure text-to-image"],
              good_examples=["use the uploaded face 100% as reference"],
              bad_examples=["make it look like the picture"],
              related_patterns=["pattern-double-exposure-portrait", "pattern-cinematic-character-portrait"],
              related_recipes=["recipe-character-consistency", "recipe-reference-restyle"],
              related_styles=["style-cinematic-realism"],
              source_repositories=["freestylefly-awesome-gpt-image-2", "awesome-nano-banana-images"],
              confidence=0.9, tags=["reference", "editing"]),
    Technique(id="technique-character-consistency", name="character consistency", category="Character Consistency",
              description="Keep the same character across panels or images.",
              problem_it_solves="Models change a character's appearance between images.",
              pattern="these two characters ... same character across panels",
              implementation_guidance="Name the character, describe fixed features, reference prior images.",
              when_to_use=["comics", "storyboards", "multi-image campaigns"],
              when_not_to_use=["single image"],
              good_examples=["these two characters in a classic black and white film noir"],
              bad_examples=["a guy in every panel"],
              related_patterns=["pattern-multi-panel-comic"],
              related_recipes=["recipe-multi-panel-comic", "recipe-character-consistency"],
              related_styles=["style-cinematic-realism"],
              source_repositories=["awesome-nano-banana-images", "awesome-nano-banana-pro-prompts"],
              confidence=0.85, tags=["consistency", "character"]),
    Technique(id="technique-negative-constraints", name="negative constraints", category="Negative Constraints",
              description="Explicitly forbid unwanted elements.",
              problem_it_solves="Models add unwanted text, props, or clutter.",
              pattern="do not include [X]; no [Y]",
              implementation_guidance="List what to exclude; keep the list short and specific.",
              when_to_use=["clean product shots", "text-free storytelling"],
              when_not_to_use=["when exclusions are obvious"],
              good_examples=["do not include any words or text on the images"],
              bad_examples=["make it clean"],
              related_patterns=["pattern-multi-panel-comic", "pattern-breakout-product-hero"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-editorial-minimalism"],
              source_repositories=["awesome-nano-banana-images", "freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["constraints", "negative"]),
    Technique(id="technique-camera-lens", name="camera & lens control", category="Camera",
              description="Specify camera, lens, and depth of field.",
              problem_it_solves="Models default to generic framing.",
              pattern="[focal length] lens, [aperture], [angle]",
              implementation_guidance="Name focal length (35mm/85mm), DOF, and angle.",
              when_to_use=["photography", "portraits", "product shots"],
              when_not_to_use=["flat illustration"],
              good_examples=["professional 85mm lens photography with shallow depth of field"],
              bad_examples=["a nice photo"],
              related_patterns=["pattern-cinematic-character-portrait"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-cinematic-realism"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.9, tags=["camera", "lens"]),
    Technique(id="technique-lighting-control", name="lighting control", category="Lighting",
              description="Specify lighting style and direction.",
              problem_it_solves="Models default to flat, generic lighting.",
              pattern="[lighting style] from [direction]",
              implementation_guidance="Name the style (golden hour, soft diffused, rim) and direction.",
              when_to_use=["product ads", "portraits", "commercial"],
              when_not_to_use=["flat vector"],
              good_examples=["golden hour glow creates reflections and ripples across the water"],
              bad_examples=["good lighting"],
              related_patterns=["pattern-centered-luxury-product", "pattern-breakout-product-hero"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-luxury-commercial", "style-cinematic-realism"],
              source_repositories=["awesome-nanobanana-pro", "freestylefly-awesome-gpt-image-2"],
              confidence=0.9, tags=["lighting"]),
    Technique(id="technique-color-grading", name="color grading", category="Color Control",
              description="Specify a color palette and grade.",
              problem_it_solves="Models pick arbitrary colors.",
              pattern="[palette] color grading",
              implementation_guidance="Name the palette (warm desaturated, teal-orange) and accents.",
              when_to_use=["cinematic", "editorial", "branded"],
              when_not_to_use=["true-color product shots"],
              good_examples=["warm desaturated sepia and charcoal palette"],
              bad_examples=["nice colors"],
              related_patterns=["pattern-cinematic-character-portrait", "pattern-double-exposure-portrait"],
              related_recipes=["recipe-editorial-poster"],
              related_styles=["style-cinematic-realism", "style-retro-print"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["color", "grade"]),
    Technique(id="technique-whitespace", name="whitespace / negative space", category="Whitespace",
              description="Reserve negative space for a clean, focused composition.",
              problem_it_solves="Models fill every area with clutter.",
              pattern="reserve negative space; controlled negative space",
              implementation_guidance="State where the empty space should be and why.",
              when_to_use=["minimal posters", "product ads", "SaaS"],
              when_not_to_use=["dense infographics"],
              good_examples=["reserve negative space for the headline"],
              bad_examples=["make it minimal"],
              related_patterns=["pattern-editorial-text-first-poster", "pattern-minimal-saas-illustration"],
              related_recipes=["recipe-editorial-poster", "recipe-saas-landing-hero"],
              related_styles=["style-editorial-minimalism", "style-premium-saas"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["whitespace", "minimal"]),
    Technique(id="technique-subject-hierarchy", name="subject hierarchy", category="Composition",
              description="Compose as a scene with a clear subject hierarchy, not isolated objects.",
              problem_it_solves="Models produce flat, disconnected compositions.",
              pattern="compose it as a SCENE; subject hierarchy: [primary] -> [secondary]",
              implementation_guidance="Order subjects by importance and describe their relationship.",
              when_to_use=["product scenes", "editorial", "storytelling"],
              when_not_to_use=["single isolated object"],
              good_examples=["compose it as a SCENE, not a single isolated object"],
              bad_examples=["a product on a table"],
              related_patterns=["pattern-breakout-product-hero", "pattern-layered-depth-product-ad"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-luxury-commercial"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["composition", "hierarchy"]),
    Technique(id="technique-multi-panel-grid", name="multi-panel grid", category="Layout",
              description="Use a strict grid for multi-panel layouts.",
              problem_it_solves="Models misalign panels.",
              pattern="strict [R]x[C] grid with [N] perfectly aligned panels",
              implementation_guidance="State rows, columns, and alignment explicitly.",
              when_to_use=["comics", "campaign grids", "comparisons"],
              when_not_to_use=["single image"],
              good_examples=["strict 2-column by 3-row grid with six perfectly aligned panels"],
              bad_examples=["a grid of images"],
              related_patterns=["pattern-multi-panel-comic", "pattern-split-screen-comparison"],
              related_recipes=["recipe-multi-panel-comic"],
              related_styles=["style-modern-chinese-editorial"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["grid", "layout"]),
    Technique(id="technique-visual-hierarchy", name="visual hierarchy", category="Visual Hierarchy",
              description="Establish a clear order of visual importance.",
              problem_it_solves="Models give equal weight to everything.",
              pattern="headline first, then supporting text, then illustration",
              implementation_guidance="Rank elements and state their relative size/emphasis.",
              when_to_use=["posters", "infographics", "ads"],
              when_not_to_use=["single-subject photography"],
              good_examples=["headline first, then supporting text, then illustration"],
              bad_examples=["some text and a picture"],
              related_patterns=["pattern-editorial-text-first-poster", "pattern-magazine-infographic"],
              related_recipes=["recipe-editorial-poster", "recipe-infographic"],
              related_styles=["style-editorial-minimalism", "style-modern-chinese-editorial"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.9, tags=["hierarchy", "layout"]),
    Technique(id="technique-templated-variables", name="templated variables", category="Prompt Structure",
              description="Use [VARIABLE] placeholders to make a prompt reusable.",
              problem_it_solves="One-off prompts can't be reused across products/brands.",
              pattern="[BRAND] [PRODUCT NAME] - [shape], [label], [color]",
              implementation_guidance="Declare variables and fill them per use.",
              when_to_use=["product templates", "campaign systems"],
              when_not_to_use=["one-off art"],
              good_examples=["Product: [BRAND] [PRODUCT NAME] - [bottle shape]"],
              bad_examples=["a specific product"],
              related_patterns=["pattern-centered-luxury-product"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-luxury-commercial"],
              source_repositories=["awesome-nanobanana-pro"],
              confidence=0.8, tags=["template", "variables"]),
    Technique(id="technique-structured-json", name="structured JSON prompting", category="Prompt Structure",
              description="Use a typed JSON schema (meta/subject/scene) for reproducible prompts.",
              problem_it_solves="Prose prompts are hard to reuse and compare.",
              pattern="{\"meta\": {...}, \"subject\": [...], \"scene\": {...}}",
              implementation_guidance="Declare aspect_ratio, guidance, typed subjects, and scene.",
              when_to_use=["reproducible pipelines", "agent workflows"],
              when_not_to_use=["casual one-off prompts"],
              good_examples=["a JSON schema with typed subject and scene"],
              bad_examples=["a long prose blob"],
              related_patterns=["pattern-breakout-product-hero"],
              related_recipes=["recipe-product-hero-ad"],
              related_styles=["style-3d-commercial"],
              source_repositories=["nano-banana-json-schema", "gpt-image2-skill"],
              confidence=0.75, tags=["json", "structured"]),
]

# --------------------------------------------------------------------------- patterns

PATTERNS = [
    VisualPattern(id="pattern-breakout-product-hero", name="Breakout Product Hero",
                  aliases=["product hero", "breakout"],
                  category="product advertisement",
                  description="Hero product with forced perspective, foreground overlap, and particles.",
                  visual_goal="Make the product feel dynamic and premium.",
                  best_for=["product ads", "hero visuals", "launch campaigns"],
                  not_good_for=["text-heavy posters", "documentary"],
                  composition="hero object + forced perspective + foreground overlap",
                  visual_hierarchy="product first, supporting elements second",
                  subject_placement="centered or three-quarter, breaking the frame",
                  foreground="overlapping particles or fragments",
                  midground="the hero product",
                  background="clean gradient or controlled environment",
                  perspective="forced perspective, slight low angle",
                  lighting_strategy="commercial lighting with rim highlights",
                  color_strategy="product color + neutral background + accent",
                  typography_strategy="minimal, reserved for brand",
                  negative_space_strategy="controlled negative space around the product",
                  supporting_elements=["particles", "secondary supporting elements"],
                  prompt_structure=["Product", "Scene", "Composition", "Lighting", "Style", "Constraints"],
                  constraints=["preserve product geometry", "protect branding"],
                  common_failures=["product distortion", "cluttered background"],
                  related_styles=["style-luxury-commercial", "style-3d-commercial"],
                  related_techniques=["technique-product-preservation", "technique-subject-hierarchy", "technique-lighting-control"],
                  related_recipes=["recipe-product-hero-ad"],
                  example_cases=["case-fintech-card", "case-saas-hero"],
                  source_repositories=["freestylefly-awesome-gpt-image-2", "awesome-nanobanana-pro"],
                  confidence=0.85, tags=["product", "hero", "commercial"]),
    VisualPattern(id="pattern-editorial-text-first-poster", name="Editorial Text-first Poster",
                  aliases=["text-first poster", "editorial poster"],
                  category="poster",
                  description="Headline-first layout with supporting text and illustration.",
                  visual_goal="Communicate a message clearly and elegantly.",
                  best_for=["recruitment posters", "editorial covers", "announcements"],
                  not_good_for=["pure product shots"],
                  composition="text-first with a single focal point",
                  visual_hierarchy="headline -> supporting text -> illustration",
                  subject_placement="headline dominant, illustration supporting",
                  foreground="headline",
                  midground="supporting text",
                  background="clean or subtle texture",
                  perspective="flat, editorial",
                  lighting_strategy="even, soft",
                  color_strategy="muted palette + 1-2 accents",
                  typography_strategy="strong headline, refined supporting type",
                  negative_space_strategy="generous margins",
                  supporting_elements=["small illustration or icon"],
                  prompt_structure=["Format", "Visual goal", "Layout", "Hierarchy", "Style", "Color", "Typography", "Constraints"],
                  constraints=["text readability first", "low density"],
                  common_failures=["text garble", "cluttered layout"],
                  related_styles=["style-editorial-minimalism", "style-modern-chinese-editorial", "style-retro-print"],
                  related_techniques=["technique-text-rendering", "technique-visual-hierarchy", "technique-whitespace"],
                  related_recipes=["recipe-editorial-poster", "recipe-xiaohongshu-info-card"],
                  example_cases=["case-xiaohongshu-recruit"],
                  source_repositories=["freestylefly-awesome-gpt-image-2", "rednote-director-skill"],
                  confidence=0.9, tags=["poster", "editorial", "text"]),
    VisualPattern(id="pattern-centered-luxury-product", name="Centered Luxury Product Shot",
                  aliases=["luxury product", "floating product"],
                  category="product advertisement",
                  description="Centered product on dark water/reflection with flowers and golden hour.",
                  visual_goal="Premium, ethereal product presentation.",
                  best_for=["luxury product ads", "perfume", "beverages"],
                  not_good_for=["budget products", "text-heavy"],
                  composition="centered product + reflection + surrounding elements",
                  visual_hierarchy="product first, reflection second",
                  subject_placement="centered, floating",
                  foreground="reflection/ripples",
                  midground="the product",
                  background="dark water or gradient",
                  perspective="eye-level, slight low angle",
                  lighting_strategy="golden hour glow, reflections",
                  color_strategy="deep tones + gold accents",
                  typography_strategy="minimal",
                  negative_space_strategy="controlled around the product",
                  supporting_elements=["flowers", "ripples"],
                  prompt_structure=["Product", "Scene", "Lighting", "Mood", "Style", "Constraints"],
                  constraints=["preserve product geometry"],
                  common_failures=["product distortion", "over-cluttered water"],
                  related_styles=["style-luxury-commercial"],
                  related_techniques=["technique-lighting-control", "technique-templated-variables", "technique-product-preservation"],
                  related_recipes=["recipe-product-hero-ad"],
                  example_cases=["case-fintech-card"],
                  source_repositories=["awesome-nanobanana-pro"],
                  confidence=0.85, tags=["luxury", "product", "reflection"]),
    VisualPattern(id="pattern-cinematic-character-portrait", name="Cinematic Character Portrait",
                  aliases=["portrait", "cinematic portrait"],
                  category="photography",
                  description="Subject + 85mm + shallow DOF + editorial mood.",
                  visual_goal="A premium, editorial portrait.",
                  best_for=["portraits", "fashion", "character shots"],
                  not_good_for=["product ads"],
                  composition="subject-forward, rule of thirds",
                  visual_hierarchy="face first, environment second",
                  subject_placement="off-center or centered, eye-level",
                  foreground="soft bokeh",
                  midground="the subject",
                  background="minimal or environmental",
                  perspective="eye-level, 85mm",
                  lighting_strategy="soft key + rim, high contrast",
                  color_strategy="warm desaturated or teal-orange",
                  typography_strategy="n/a",
                  negative_space_strategy="controlled background",
                  supporting_elements=["film grain", "light leak"],
                  prompt_structure=["Subject", "Environment", "Composition", "Camera", "Lens", "Lighting", "Color", "Mood", "Constraints"],
                  constraints=["natural skin texture", "no over-smoothing"],
                  common_failures=["plastic skin", "flat lighting"],
                  related_styles=["style-cinematic-realism"],
                  related_techniques=["technique-camera-lens", "technique-lighting-control", "technique-color-grading"],
                  related_recipes=["recipe-character-consistency"],
                  example_cases=["case-cinematic-portrait"],
                  source_repositories=["freestylefly-awesome-gpt-image-2"],
                  confidence=0.9, tags=["portrait", "cinematic", "photography"]),
    VisualPattern(id="pattern-magazine-infographic", name="Magazine Infographic",
                  aliases=["infographic", "editorial infographic"],
                  category="infographic",
                  description="Editorial layout + data + typography + whitespace.",
                  visual_goal="Communicate data clearly and beautifully.",
                  best_for=["data visualization", "educational cards", "reports"],
                  not_good_for=["pure photography"],
                  composition="structured grid with data hierarchy",
                  visual_hierarchy="headline -> key data -> detail",
                  subject_placement="data blocks in a grid",
                  foreground="headline",
                  midground="charts/data",
                  background="clean paper",
                  perspective="flat, editorial",
                  lighting_strategy="even",
                  color_strategy="muted + accent for key data",
                  typography_strategy="clear hierarchy, readable labels",
                  negative_space_strategy="generous between blocks",
                  supporting_elements=["icons", "charts"],
                  prompt_structure=["Format", "Visual goal", "Layout", "Hierarchy", "Style", "Color", "Typography", "Constraints"],
                  constraints=["text readability first", "accurate data"],
                  common_failures=["text garble", "data mislabel"],
                  related_styles=["style-modern-chinese-editorial", "style-editorial-minimalism"],
                  related_techniques=["technique-text-rendering", "technique-visual-hierarchy"],
                  related_recipes=["recipe-infographic"],
                  example_cases=["case-chinese-infographic"],
                  source_repositories=["freestylefly-awesome-gpt-image-2", "ai-image-prompt-cookbook"],
                  confidence=0.85, tags=["infographic", "data", "editorial"]),
    VisualPattern(id="pattern-multi-panel-comic", name="Multi-panel Comic",
                  aliases=["comic", "storyboard", "多格漫画"],
                  category="comic",
                  description="Grid of sequential panels with character consistency.",
                  visual_goal="Tell a story across panels.",
                  best_for=["comics", "storyboards", "sequential art"],
                  not_good_for=["single image"],
                  composition="strict grid, sequential panels",
                  visual_hierarchy="story flow across panels",
                  subject_placement="characters consistent across panels",
                  foreground="action",
                  midground="characters",
                  background="scene per panel",
                  perspective="varies per panel",
                  lighting_strategy="consistent per scene",
                  color_strategy="consistent palette",
                  typography_strategy="minimal or none",
                  negative_space_strategy="panel gutters",
                  supporting_elements=["speech bubbles (optional)"],
                  prompt_structure=["Format", "Story", "Layout", "Style", "Color", "Constraints"],
                  constraints=["character consistency", "no text unless specified"],
                  common_failures=["character drift", "panel misalignment"],
                  related_styles=["style-cinematic-realism", "style-flat-vector"],
                  related_techniques=["technique-character-consistency", "technique-multi-panel-grid", "technique-negative-constraints"],
                  related_recipes=["recipe-multi-panel-comic"],
                  example_cases=["case-multi-panel-comic"],
                  source_repositories=["awesome-nano-banana-images", "awesome-nano-banana-pro-prompts"],
                  confidence=0.85, tags=["comic", "storyboard", "sequential"]),
    VisualPattern(id="pattern-minimal-saas-illustration", name="Minimal SaaS Illustration",
                  aliases=["saas illustration", "flat illustration"],
                  category="product hero",
                  description="Flat vector + device + negative space + brand color.",
                  visual_goal="A clean, modern product visual.",
                  best_for=["SaaS landing heroes", "app marketing"],
                  not_good_for=["photoreal product shots"],
                  composition="device hero with minimal illustration",
                  visual_hierarchy="product/device first",
                  subject_placement="centered device",
                  foreground="device",
                  midground="minimal illustration",
                  background="brand color or neutral",
                  perspective="front or slight angle",
                  lighting_strategy="soft, even",
                  color_strategy="brand color + neutral",
                  typography_strategy="clean sans-serif",
                  negative_space_strategy="generous",
                  supporting_elements=["floating UI cards"],
                  prompt_structure=["Product", "Scene", "Composition", "Style", "Color", "Constraints"],
                  constraints=["flat, no photorealism"],
                  common_failures=["clutter", "inconsistent brand color"],
                  related_styles=["style-premium-saas", "style-flat-vector"],
                  related_techniques=["technique-whitespace", "technique-visual-hierarchy"],
                  related_recipes=["recipe-saas-landing-hero"],
                  example_cases=["case-saas-hero"],
                  source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
                  confidence=0.85, tags=["saas", "flat", "hero"]),
    VisualPattern(id="pattern-hero-device-composition", name="Hero Device Composition",
                  aliases=["device hero", "app hero"],
                  category="product hero",
                  description="Device + product + environment, layered depth.",
                  visual_goal="Show the product in a real context.",
                  best_for=["app screenshots", "device marketing"],
                  not_good_for=["text-heavy posters"],
                  composition="device + environment + layered depth",
                  visual_hierarchy="device first, environment second",
                  subject_placement="device centered or angled",
                  foreground="device",
                  midground="supporting UI",
                  background="environment",
                  perspective="three-quarter angle",
                  lighting_strategy="soft studio",
                  color_strategy="brand + neutral",
                  typography_strategy="UI text on device",
                  negative_space_strategy="controlled",
                  supporting_elements=["floating UI elements"],
                  prompt_structure=["Product", "Scene", "Composition", "Style", "Constraints"],
                  constraints=["preserve UI text"],
                  common_failures=["UI text garble"],
                  related_styles=["style-premium-saas", "style-3d-commercial"],
                  related_techniques=["technique-text-rendering", "technique-product-preservation"],
                  related_recipes=["recipe-saas-landing-hero", "recipe-app-screenshot-ad"],
                  example_cases=["case-saas-hero"],
                  source_repositories=["gpt-image2-skill"],
                  confidence=0.8, tags=["device", "app", "hero"]),
    VisualPattern(id="pattern-double-exposure-portrait", name="Double-exposure Portrait",
                  aliases=["double exposure", "双重曝光"],
                  category="photography",
                  description="Subject + layered semi-transparent profile.",
                  visual_goal="A striking, layered portrait.",
                  best_for=["fashion editorials", "art portraits"],
                  not_good_for=["product ads"],
                  composition="layered semi-transparent profile + full figure",
                  visual_hierarchy="face first, layered profile second",
                  subject_placement="profile left, figure right",
                  foreground="semi-transparent profile",
                  midground="full figure",
                  background="minimal studio",
                  perspective="eye-level",
                  lighting_strategy="soft cinematic, high contrast",
                  color_strategy="warm desaturated sepia/charcoal",
                  typography_strategy="n/a",
                  negative_space_strategy="minimal background",
                  supporting_elements=["light leak", "film grain"],
                  prompt_structure=["Subject", "Composition", "Lighting", "Color", "Mood", "Constraints"],
                  constraints=["natural skin texture"],
                  common_failures=["muddy layers"],
                  related_styles=["style-cinematic-realism"],
                  related_techniques=["technique-reference-image", "technique-color-grading", "technique-camera-lens"],
                  related_recipes=["recipe-character-consistency"],
                  example_cases=["case-cinematic-portrait"],
                  source_repositories=["freestylefly-awesome-gpt-image-2"],
                  confidence=0.8, tags=["portrait", "double-exposure", "editorial"]),
    VisualPattern(id="pattern-layered-depth-product-ad", name="Layered Depth Product Ad",
                  aliases=["layered product", "depth ad"],
                  category="product advertisement",
                  description="Foreground/midground/background separation for depth.",
                  visual_goal="A product ad with real depth.",
                  best_for=["product ads", "campaigns"],
                  not_good_for=["flat illustration"],
                  composition="foreground/midground/background separation",
                  visual_hierarchy="product in midground, depth around it",
                  subject_placement="product midground",
                  foreground="blurred foreground element",
                  midground="product",
                  background="environment",
                  perspective="slight low angle",
                  lighting_strategy="commercial, layered",
                  color_strategy="product + environment",
                  typography_strategy="minimal",
                  negative_space_strategy="controlled",
                  supporting_elements=["foreground bokeh"],
                  prompt_structure=["Product", "Scene", "Composition", "Lighting", "Constraints"],
                  constraints=["preserve product geometry"],
                  common_failures=["flat composition"],
                  related_styles=["style-luxury-commercial", "style-3d-commercial"],
                  related_techniques=["technique-subject-hierarchy", "technique-lighting-control"],
                  related_recipes=["recipe-product-hero-ad"],
                  example_cases=["case-fintech-card"],
                  source_repositories=["freestylefly-awesome-gpt-image-2"],
                  confidence=0.8, tags=["product", "depth", "commercial"]),
]

# --------------------------------------------------------------------------- recipes

RECIPES = [
    Recipe(id="recipe-product-hero-ad", name="Product Hero Ad", category="product advertisement",
           goal="A premium product hero image that preserves the product and sells it.",
           description="The canonical method for a product hero advertisement.",
           required_inputs=["product name", "product description", "brand"],
           optional_inputs=["visual metaphor", "environment", "text"],
           workflow=["identify hero product", "preserve geometry", "choose metaphor", "separate layers", "light", "support", "negative space", "brand", "text", "decorate"],
           steps=[
               "Identify the hero product and its critical geometry.",
               "Preserve critical product geometry and branding.",
               "Select a primary visual metaphor (breakout, floating, reflection).",
               "Create strong foreground/background separation.",
               "Choose commercial lighting (rim, golden hour, soft studio).",
               "Add controlled supporting elements (particles, flowers, ripples).",
               "Reserve negative space for the product and any text.",
               "Protect branding (exact name, logo, colors).",
               "Add text-rendering constraints if text is present.",
               "Remove irrelevant decorative elements.",
           ],
           decision_points=["metaphor choice", "lighting style", "text or no text"],
           recommended_patterns=["pattern-breakout-product-hero", "pattern-centered-luxury-product", "pattern-layered-depth-product-ad"],
           recommended_styles=["style-luxury-commercial", "style-3d-commercial"],
           recommended_techniques=["technique-product-preservation", "technique-brand-preservation", "technique-lighting-control", "technique-subject-hierarchy"],
           prompt_structure=["Product", "Scene", "Composition", "Lighting", "Style", "Supporting elements", "Negative space", "Constraints"],
           composition_guidance="Hero product centered or three-quarter, strong depth.",
           text_guidance="Quote exact text; keep it short; specify font style.",
           constraints=["preserve product geometry", "protect branding"],
           common_failures=["product distortion", "cluttered background", "brand garble"],
           failure_recovery=["re-state product geometry", "add negative constraints", "quote brand name"],
           example_cases=["case-fintech-card", "case-saas-hero"],
           source_repositories=["freestylefly-awesome-gpt-image-2", "awesome-nanobanana-pro", "gpt-image2-skill"],
           confidence=0.9, tags=["product", "ad", "commercial"]),
    Recipe(id="recipe-editorial-poster", name="Editorial Poster", category="poster",
           goal="A text-first editorial poster with clear hierarchy.",
           description="The canonical method for an editorial poster.",
           required_inputs=["headline", "supporting text"],
           optional_inputs=["illustration", "brand", "date"],
           workflow=["format", "goal", "layout", "headline", "text", "illustration", "style", "color", "type", "details", "constraints"],
           steps=[
               "Set canvas/format and aspect ratio.",
               "Define the visual goal and message.",
               "Choose the layout (text-first, grid, centered).",
               "Place the headline as the dominant element.",
               "Add supporting text with clear hierarchy.",
               "Add a supporting illustration or icon.",
               "Select the style (editorial minimalism, retro, Swiss).",
               "Choose a restrained color palette.",
               "Specify typography (headline + supporting).",
               "Add details and constraints (text readability, low density).",
           ],
           decision_points=["text-first vs image-first", "style", "palette"],
           recommended_patterns=["pattern-editorial-text-first-poster"],
           recommended_styles=["style-editorial-minimalism", "style-modern-chinese-editorial", "style-retro-print", "style-swiss-editorial"],
           recommended_techniques=["technique-text-rendering", "technique-visual-hierarchy", "technique-whitespace"],
           prompt_structure=["Format", "Visual goal", "Layout", "Hierarchy", "Style", "Color", "Typography", "Constraints"],
           composition_guidance="Headline first, then supporting text, then illustration.",
           text_guidance="Quote every string; specify font style; keep text short.",
           constraints=["text readability first", "low density"],
           common_failures=["text garble", "cluttered layout"],
           failure_recovery=["quote text exactly", "reduce element count"],
           example_cases=["case-xiaohongshu-recruit"],
           source_repositories=["freestylefly-awesome-gpt-image-2", "rednote-director-skill"],
           confidence=0.9, tags=["poster", "editorial", "text"]),
    Recipe(id="recipe-xiaohongshu-info-card", name="Xiaohongshu Information Card", category="social media poster",
           goal="A platform-aware Xiaohongshu cover that prioritizes text readability.",
           description="The method for a Xiaohongshu (RedNote) information card.",
           required_inputs=["topic", "headline"],
           optional_inputs=["sub-points", "brand", "illustration"],
           workflow=["platform", "ratio", "readability", "minimalism", "density", "cover", "pages"],
           steps=[
               "Confirm the platform (Xiaohongshu) and aspect ratio (3:4).",
               "Prioritize text readability above all else.",
               "Choose editorial minimalism with a restrained palette.",
               "Keep visual density low.",
               "Design the cover as the primary card.",
               "Plan inner pages/carousel if needed.",
           ],
           decision_points=["cover vs carousel", "palette"],
           recommended_patterns=["pattern-editorial-text-first-poster"],
           recommended_styles=["style-editorial-minimalism", "style-modern-chinese-editorial"],
           recommended_techniques=["technique-text-rendering", "technique-visual-hierarchy", "technique-whitespace"],
           prompt_structure=["Format", "Visual goal", "Layout", "Hierarchy", "Style", "Color", "Typography", "Constraints"],
           composition_guidance="Text-first, generous margins, single focal point.",
           text_guidance="Quote exact Chinese text; specify font style.",
           constraints=["text readability first", "low density", "3:4"],
           common_failures=["text garble", "too dense"],
           failure_recovery=["quote text exactly", "increase whitespace"],
           example_cases=["case-xiaohongshu-recruit"],
           source_repositories=["rednote-director-skill", "ai-image-prompt-cookbook"],
           confidence=0.85, tags=["xiaohongshu", "social", "cover"]),
    Recipe(id="recipe-character-consistency", name="Character Consistency", category="character",
           goal="Keep the same character across images or panels.",
           description="The method for consistent character generation.",
           required_inputs=["character description", "reference image (optional)"],
           optional_inputs=["outfit", "scene", "panels"],
           workflow=["reference", "identity", "restyle", "geometry", "consistency"],
           steps=[
               "Provide a reference image or a detailed character description.",
               "Preserve the character's identity (face, hair, build).",
               "Apply the new styling or scene.",
               "Keep the character's geometry consistent.",
               "Re-anchor with a consolidated prompt if drift occurs.",
           ],
           decision_points=["reference vs description", "restyle vs new scene"],
           recommended_patterns=["pattern-cinematic-character-portrait", "pattern-double-exposure-portrait"],
           recommended_styles=["style-cinematic-realism"],
           recommended_techniques=["technique-reference-image", "technique-character-consistency", "technique-camera-lens"],
           prompt_structure=["Subject", "Reference", "Style", "Composition", "Lighting", "Constraints"],
           composition_guidance="Subject-forward, consistent framing.",
           text_guidance="n/a",
           constraints=["preserve identity", "natural skin texture"],
           common_failures=["identity drift", "plastic skin"],
           failure_recovery=["re-state identity", "re-anchor with reference"],
           example_cases=["case-cinematic-portrait"],
           source_repositories=["awesome-nano-banana-images", "freestylefly-awesome-gpt-image-2"],
           confidence=0.85, tags=["character", "consistency", "portrait"]),
    Recipe(id="recipe-reference-restyle", name="Reference Image Restyle", category="image editing",
           goal="Restyle an input image while preserving its subject.",
           description="The method for reference-image restyling.",
           required_inputs=["input image", "target style"],
           optional_inputs=["composition change", "environment"],
           workflow=["input", "subject", "style", "composition", "output"],
           steps=[
               "Provide the input image.",
               "Identify the subject to preserve.",
               "Apply the new style.",
               "Preserve or change the composition as needed.",
               "Generate the restyled output.",
           ],
           decision_points=["preserve vs change composition"],
           recommended_patterns=["pattern-double-exposure-portrait"],
           recommended_styles=["style-cinematic-realism", "style-flat-vector"],
           recommended_techniques=["technique-reference-image", "technique-character-consistency"],
           prompt_structure=["Subject", "Reference", "Style", "Composition", "Constraints"],
           composition_guidance="Preserve the subject's core composition.",
           text_guidance="n/a",
           constraints=["preserve subject identity"],
           common_failures=["subject drift", "style bleed"],
           failure_recovery=["re-state the subject", "strengthen the style"],
           example_cases=["case-cinematic-portrait"],
           source_repositories=["awesome-nano-banana-images", "freestylefly-awesome-gpt-image-2"],
           confidence=0.8, tags=["editing", "restyle", "reference"]),
    Recipe(id="recipe-multi-panel-comic", name="Multi-panel Comic", category="comic",
           goal="A multi-panel comic with consistent characters.",
           description="The method for sequential art.",
           required_inputs=["story", "characters"],
           optional_inputs=["panel count", "style", "text"],
           workflow=["story", "grid", "consistency", "no-text", "sequential"],
           steps=[
               "Define the story and its beats.",
               "Choose a panel grid (e.g. 2x3).",
               "Keep characters consistent across panels.",
               "Decide whether to include text (often none).",
               "Order panels for sequential reading.",
           ],
           decision_points=["panel count", "text or no text"],
           recommended_patterns=["pattern-multi-panel-comic"],
           recommended_styles=["style-cinematic-realism", "style-flat-vector"],
           recommended_techniques=["technique-character-consistency", "technique-multi-panel-grid", "technique-negative-constraints"],
           prompt_structure=["Format", "Story", "Layout", "Style", "Color", "Constraints"],
           composition_guidance="Strict grid, sequential flow.",
           text_guidance="Omit text unless explicitly requested.",
           constraints=["character consistency", "no text unless specified"],
           common_failures=["character drift", "panel misalignment"],
           failure_recovery=["re-state characters", "re-state grid"],
           example_cases=["case-multi-panel-comic"],
           source_repositories=["awesome-nano-banana-images", "awesome-nano-banana-pro-prompts"],
           confidence=0.85, tags=["comic", "storyboard", "sequential"]),
    Recipe(id="recipe-infographic", name="Infographic", category="infographic",
           goal="A clear, beautiful data visualization.",
           description="The method for an infographic.",
           required_inputs=["data", "topic"],
           optional_inputs=["chart type", "brand", "icons"],
           workflow=["data", "hierarchy", "chart", "type", "color", "whitespace"],
           steps=[
               "Organize the data and its key message.",
               "Establish a clear hierarchy (headline -> key data -> detail).",
               "Choose the chart type.",
               "Specify typography for labels and numbers.",
               "Choose a restrained color palette.",
               "Reserve whitespace between blocks.",
           ],
           decision_points=["chart type", "palette"],
           recommended_patterns=["pattern-magazine-infographic"],
           recommended_styles=["style-modern-chinese-editorial", "style-editorial-minimalism"],
           recommended_techniques=["technique-text-rendering", "technique-visual-hierarchy"],
           prompt_structure=["Format", "Visual goal", "Layout", "Hierarchy", "Style", "Color", "Typography", "Constraints"],
           composition_guidance="Structured grid, data hierarchy.",
           text_guidance="Quote exact labels and numbers; specify font style.",
           constraints=["text readability first", "accurate data"],
           common_failures=["text garble", "data mislabel"],
           failure_recovery=["quote labels exactly", "simplify the chart"],
           example_cases=["case-chinese-infographic"],
           source_repositories=["freestylefly-awesome-gpt-image-2", "ai-image-prompt-cookbook"],
           confidence=0.85, tags=["infographic", "data", "editorial"]),
    Recipe(id="recipe-fintech-card-ad", name="Fintech Card Ad", category="product advertisement",
           goal="A fintech card advertisement with exact numbers and clean hierarchy.",
           description="The method for a fintech card ad.",
           required_inputs=["card name", "key numbers", "brand"],
           optional_inputs=["benefits", "environment"],
           workflow=["product", "numbers", "hierarchy", "ux", "brand", "text"],
           steps=[
               "Identify the card product and its design.",
               "Specify exact numbers and labels.",
               "Establish a clean hierarchy.",
               "Make the UI believable (wallet UX).",
               "Protect the brand.",
               "Add text-rendering constraints.",
           ],
           decision_points=["card design", "key numbers"],
           recommended_patterns=["pattern-breakout-product-hero", "pattern-centered-luxury-product"],
           recommended_styles=["style-luxury-commercial", "style-3d-commercial"],
           recommended_techniques=["technique-text-rendering", "technique-brand-preservation", "technique-product-preservation"],
           prompt_structure=["Product", "Scene", "Composition", "Lighting", "Style", "Constraints"],
           composition_guidance="Card hero, clean hierarchy, believable UX.",
           text_guidance="Quote exact numbers and labels; crisp, clean type.",
           constraints=["exact numbers", "clean hierarchy", "protect brand"],
           common_failures=["number garble", "unbelievable UX"],
           failure_recovery=["quote numbers exactly", "simplify the UI"],
           example_cases=["case-fintech-card"],
           source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
           confidence=0.85, tags=["fintech", "card", "ad"]),
    Recipe(id="recipe-saas-landing-hero", name="SaaS Landing Hero", category="product hero",
           goal="A clean SaaS landing hero visual.",
           description="The method for a SaaS landing hero.",
           required_inputs=["product name", "brand color"],
           optional_inputs=["device", "illustration", "headline"],
           workflow=["product", "device", "illustration", "space", "color"],
           steps=[
               "Identify the product and its core value.",
               "Choose a device or hero composition.",
               "Add minimal illustration.",
               "Reserve negative space.",
               "Apply the brand color.",
           ],
           decision_points=["device vs illustration", "flat vs 3D"],
           recommended_patterns=["pattern-minimal-saas-illustration", "pattern-hero-device-composition"],
           recommended_styles=["style-premium-saas", "style-flat-vector"],
           recommended_techniques=["technique-whitespace", "technique-visual-hierarchy"],
           prompt_structure=["Product", "Scene", "Composition", "Style", "Color", "Constraints"],
           composition_guidance="Device hero, minimal illustration, generous space.",
           text_guidance="Quote any UI text; keep it short.",
           constraints=["flat or clean 3D", "brand color"],
           common_failures=["clutter", "inconsistent brand color"],
           failure_recovery=["reduce elements", "re-state brand color"],
           example_cases=["case-saas-hero"],
           source_repositories=["gpt-image2-skill", "freestylefly-awesome-gpt-image-2"],
           confidence=0.85, tags=["saas", "hero", "landing"]),
    Recipe(id="recipe-app-screenshot-ad", name="App Screenshot Ad", category="product hero",
           goal="An app screenshot advertisement.",
           description="The method for an app screenshot ad.",
           required_inputs=["app name", "screenshot", "platform"],
           optional_inputs=["caption", "device frame"],
           workflow=["app", "screenshot", "device", "caption", "platform"],
           steps=[
               "Identify the app and its screenshot.",
               "Place the screenshot in a device frame.",
               "Add a caption or headline.",
               "Respect platform constraints.",
           ],
           decision_points=["device frame", "caption"],
           recommended_patterns=["pattern-hero-device-composition"],
           recommended_styles=["style-premium-saas"],
           recommended_techniques=["technique-text-rendering", "technique-product-preservation"],
           prompt_structure=["Product", "Scene", "Composition", "Style", "Constraints"],
           composition_guidance="Device hero with screenshot.",
           text_guidance="Quote exact UI text and caption.",
           constraints=["preserve UI text", "platform constraints"],
           common_failures=["UI text garble"],
           failure_recovery=["quote UI text exactly"],
           example_cases=["case-saas-hero"],
           source_repositories=["gpt-image2-skill"],
           confidence=0.8, tags=["app", "screenshot", "ad"]),
]

# --------------------------------------------------------------------------- dna

DNA = [
    PromptDna(id="dna-breakout-product-hero", name="Breakout Product Hero DNA", category="product",
              description="The composable structure of a breakout product hero.",
              components=["hero object", "forced perspective", "foreground overlap", "frame/device breakout", "particles", "commercial lighting", "secondary supporting elements", "controlled negative space"],
              pattern="hero object + forced perspective + foreground overlap + particles + commercial lighting + negative space",
              variables=["product", "metaphor", "lighting", "particles"],
              best_for=["product ads", "launch campaigns"],
              related_patterns=["pattern-breakout-product-hero"],
              related_techniques=["technique-product-preservation", "technique-subject-hierarchy"],
              related_styles=["style-luxury-commercial", "style-3d-commercial"],
              source_families=["product hero"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.85, tags=["product", "hero", "dna"]),
    PromptDna(id="dna-editorial-text-first-poster", name="Editorial Text-first Poster DNA", category="poster",
              description="The composable structure of a text-first editorial poster.",
              components=["format", "headline", "supporting text", "illustration", "style", "color", "typography", "negative space"],
              pattern="format + headline + supporting text + illustration + style + color + typography + negative space",
              variables=["headline", "supporting text", "style", "palette"],
              best_for=["posters", "covers", "announcements"],
              related_patterns=["pattern-editorial-text-first-poster"],
              related_techniques=["technique-text-rendering", "technique-visual-hierarchy"],
              related_styles=["style-editorial-minimalism", "style-modern-chinese-editorial"],
              source_families=["editorial poster"],
              source_repositories=["freestylefly-awesome-gpt-image-2", "rednote-director-skill"],
              confidence=0.9, tags=["poster", "editorial", "dna"]),
    PromptDna(id="dna-direct-flash-editorial-portrait", name="Direct Flash Editorial Portrait DNA", category="photography",
              description="The composable structure of a direct-flash editorial portrait.",
              components=["subject", "direct flash", "dark ambient environment", "35mm framing", "natural skin texture", "slightly candid composition", "editorial mood"],
              pattern="subject + direct flash + dark ambient + 35mm + natural skin + candid + editorial mood",
              variables=["subject", "environment", "mood"],
              best_for=["editorial portraits", "fashion"],
              related_patterns=["pattern-cinematic-character-portrait"],
              related_techniques=["technique-camera-lens", "technique-lighting-control"],
              related_styles=["style-cinematic-realism"],
              source_families=["editorial portrait"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.8, tags=["portrait", "flash", "dna"]),
    PromptDna(id="dna-luxury-product-shot", name="Luxury Product Shot DNA", category="product",
              description="The composable structure of a luxury product shot.",
              components=["product", "dark water", "flowers", "golden hour glow", "reflections", "shallow depth of field", "high-end commercial photography"],
              pattern="product + dark water + flowers + golden hour + reflections + shallow DOF + commercial",
              variables=["product", "flower type", "lighting style"],
              best_for=["luxury product ads", "perfume", "beverages"],
              related_patterns=["pattern-centered-luxury-product"],
              related_techniques=["technique-lighting-control", "technique-templated-variables"],
              related_styles=["style-luxury-commercial"],
              source_families=["luxury product"],
              source_repositories=["awesome-nanobanana-pro"],
              confidence=0.85, tags=["luxury", "product", "dna"]),
    PromptDna(id="dna-cinematic-portrait", name="Cinematic Portrait DNA", category="photography",
              description="The composable structure of a cinematic portrait.",
              components=["subject", "85mm lens", "shallow depth of field", "soft key + rim light", "warm desaturated grade", "film grain", "editorial mood"],
              pattern="subject + 85mm + shallow DOF + key/rim light + warm grade + film grain + editorial mood",
              variables=["subject", "environment", "grade"],
              best_for=["portraits", "fashion", "character shots"],
              related_patterns=["pattern-cinematic-character-portrait"],
              related_techniques=["technique-camera-lens", "technique-lighting-control", "technique-color-grading"],
              related_styles=["style-cinematic-realism"],
              source_families=["cinematic portrait"],
              source_repositories=["freestylefly-awesome-gpt-image-2"],
              confidence=0.9, tags=["portrait", "cinematic", "dna"]),
]

# --------------------------------------------------------------------------- cases

CASES = [
    Case(id="case-xiaohongshu-recruit", title="AI 公司招聘小红书封面",
         category="social media poster", use_case="recruitment marketing",
         user_intent="A Xiaohongshu recruitment cover for an AI company, 3:4, minimal, professional.",
         input_type="text-to-image", reference_requirements="none",
         source="synthetic", model="gpt-image-2",
         original_prompt="A 3:4 Xiaohongshu recruitment cover for an AI company. Text-first editorial layout. Headline \"我们在招人\" in bold modern Chinese sans-serif. Supporting text \"AI 工程师 · 产品经理 · 设计师\" in smaller refined type. Minimal illustration of a small geometric AI motif. Editorial minimalism style, muted off-white background, one accent color. Generous negative space, low visual density, text readability first.",
         visual_intent="A clean, text-first recruitment cover.",
         subject="recruitment headline", environment="clean off-white background",
         composition="text-first, single focal point", lighting="even, soft",
         camera="n/a", lens="n/a", perspective="flat editorial",
         style="editorial minimalism", color="off-white + one accent",
         materials="paper", typography="bold Chinese sans-serif headline",
         layout="headline top, supporting text below, small motif",
         supporting_elements=["geometric AI motif"],
         techniques=["text rendering", "visual hierarchy", "whitespace"],
         constraints=["3:4", "text readability first", "low density"],
         negative_constraints=["no clutter", "no photorealism"],
         tags=["xiaohongshu", "recruitment", "editorial", "minimal"],
         pattern_ids=["pattern-editorial-text-first-poster"],
         style_ids=["style-editorial-minimalism"],
         technique_ids=["technique-text-rendering", "technique-visual-hierarchy", "technique-whitespace"],
         recipe_ids=["recipe-xiaohongshu-info-card", "recipe-editorial-poster"]),
    Case(id="case-fintech-card", title="金融科技银行卡广告",
         category="product advertisement", use_case="fintech marketing",
         user_intent="A premium fintech card advertisement.",
         input_type="text-to-image", reference_requirements="none",
         source="synthetic", model="nano-banana-pro",
         original_prompt="A premium fintech card advertisement. A dark metal credit card floating on dark water with subtle ripples and reflections. Card reads \"NOVA CARD\" in clean sans-serif. Golden hour glow creates reflections. Luxury commercial style, shallow depth of field, soft bokeh background. Preserve card geometry and branding exactly. Controlled negative space.",
         visual_intent="A premium floating card ad.",
         subject="metal credit card", environment="dark water",
         composition="centered card + reflection", lighting="golden hour glow",
         camera="eye-level", lens="shallow depth of field", perspective="slight low angle",
         style="luxury commercial", color="dark + gold accents",
         materials="metal, water", typography="clean sans-serif on card",
         layout="centered",
         supporting_elements=["ripples", "reflections"],
         techniques=["product preservation", "brand preservation", "lighting control", "text rendering"],
         constraints=["preserve card geometry", "protect branding"],
         negative_constraints=["no clutter"],
         tags=["fintech", "card", "luxury", "ad"],
         pattern_ids=["pattern-centered-luxury-product", "pattern-breakout-product-hero"],
         style_ids=["style-luxury-commercial"],
         technique_ids=["technique-product-preservation", "technique-brand-preservation", "technique-lighting-control", "technique-text-rendering"],
         recipe_ids=["recipe-fintech-card-ad", "recipe-product-hero-ad"]),
    Case(id="case-saas-hero", title="SaaS / AI 产品 Hero Visual",
         category="product hero", use_case="product marketing",
         user_intent="A clean SaaS/AI product hero visual.",
         input_type="text-to-image", reference_requirements="none",
         source="synthetic", model="gpt-image-2",
         original_prompt="A clean SaaS product hero visual. A laptop device centered with a minimal flat-vector illustration of an AI assistant interface floating around it. Premium SaaS style, brand blue accent on a neutral background. Generous negative space, flat vector, no photorealism. Clean sans-serif UI text on the device.",
         visual_intent="A clean SaaS hero with device.",
         subject="laptop device", environment="neutral background",
         composition="centered device + floating UI", lighting="soft, even",
         camera="front", lens="n/a", perspective="slight angle",
         style="premium SaaS", color="brand blue + neutral",
         materials="flat vector", typography="clean sans-serif UI",
         layout="centered device",
         supporting_elements=["floating UI cards"],
         techniques=["whitespace", "visual hierarchy", "text rendering"],
         constraints=["flat vector", "brand color"],
         negative_constraints=["no photorealism", "no clutter"],
         tags=["saas", "hero", "device", "flat"],
         pattern_ids=["pattern-minimal-saas-illustration", "pattern-hero-device-composition"],
         style_ids=["style-premium-saas"],
         technique_ids=["technique-whitespace", "technique-visual-hierarchy", "technique-text-rendering"],
         recipe_ids=["recipe-saas-landing-hero"]),
    Case(id="case-cinematic-portrait", title="写实人物摄影",
         category="photography", use_case="photography",
         user_intent="A realistic cinematic character portrait.",
         input_type="text-to-image", reference_requirements="optional reference face",
         source="synthetic", model="gpt-image-2",
         original_prompt="A cinematic character portrait. A woman with long dark hair, natural skin texture, confident expression. 85mm lens, shallow depth of field, soft key light with rim light. Warm desaturated sepia and charcoal color grade, subtle film grain. Minimal neutral studio background. Editorial mood, premium magazine quality.",
         visual_intent="A cinematic editorial portrait.",
         subject="woman with dark hair", environment="minimal studio",
         composition="subject-forward, rule of thirds", lighting="soft key + rim",
         camera="85mm", lens="shallow depth of field", perspective="eye-level",
         style="cinematic realism", color="warm desaturated sepia/charcoal",
         materials="fabric, skin", typography="n/a",
         layout="portrait",
         supporting_elements=["film grain"],
         techniques=["camera & lens control", "lighting control", "color grading"],
         constraints=["natural skin texture"],
         negative_constraints=["no over-smoothing", "no plastic skin"],
         tags=["portrait", "cinematic", "photography"],
         pattern_ids=["pattern-cinematic-character-portrait"],
         style_ids=["style-cinematic-realism"],
         technique_ids=["technique-camera-lens", "technique-lighting-control", "technique-color-grading"],
         recipe_ids=["recipe-character-consistency"]),
    Case(id="case-chinese-infographic", title="中文信息图",
         category="infographic", use_case="education",
         user_intent="A Chinese-language infographic.",
         input_type="text-to-image", reference_requirements="none",
         source="synthetic", model="gpt-image-2",
         original_prompt="A Chinese-language infographic. Editorial magazine layout. Headline \"2026 AI 趋势\" in bold Chinese serif. Three data blocks with exact numbers and labels in clean sans-serif. Modern Chinese editorial style, red and ink accents on paper white. Structured grid, generous whitespace, text readability first.",
         visual_intent="A clean Chinese infographic.",
         subject="AI trends data", environment="paper white",
         composition="structured grid", lighting="even",
         camera="n/a", lens="n/a", perspective="flat editorial",
         style="modern Chinese editorial", color="red + ink + paper white",
         materials="paper", typography="bold Chinese serif headline",
         layout="headline + three data blocks",
         supporting_elements=["icons", "charts"],
         techniques=["text rendering", "visual hierarchy"],
         constraints=["text readability first", "accurate data"],
         negative_constraints=["no clutter"],
         tags=["chinese", "infographic", "editorial", "data"],
         pattern_ids=["pattern-magazine-infographic"],
         style_ids=["style-modern-chinese-editorial"],
         technique_ids=["technique-text-rendering", "technique-visual-hierarchy"],
         recipe_ids=["recipe-infographic"]),
    Case(id="case-multi-panel-comic", title="多格漫画",
         category="comic", use_case="storytelling",
         user_intent="A multi-panel comic.",
         input_type="text-to-image", reference_requirements="character reference optional",
         source="synthetic", model="nano-banana-pro",
         original_prompt="A multi-panel comic. A strict 2-column by 3-row grid with six perfectly aligned panels. Two consistent characters — a detective and a robot — in a black and white film noir story. Character consistency across all panels. No text or words on the images; tell the story purely through imagery. Sequential art, consistent palette.",
         visual_intent="A six-panel noir comic.",
         subject="detective and robot", environment="film noir city",
         composition="2x3 grid", lighting="high contrast noir",
         camera="varies per panel", lens="n/a", perspective="varies",
         style="cinematic realism", color="black and white",
         materials="ink", typography="none",
         layout="six panels",
         supporting_elements=["none"],
         techniques=["character consistency", "multi-panel grid", "negative constraints"],
         constraints=["character consistency", "no text"],
         negative_constraints=["no words or text"],
         tags=["comic", "storyboard", "noir", "sequential"],
         pattern_ids=["pattern-multi-panel-comic"],
         style_ids=["style-cinematic-realism"],
         technique_ids=["technique-character-consistency", "technique-multi-panel-grid", "technique-negative-constraints"],
         recipe_ids=["recipe-multi-panel-comic"]),
    Case(id="case-product-hero", title="产品 Hero 广告",
         category="product advertisement", use_case="product marketing",
         user_intent="A breakout product hero ad.",
         input_type="text-to-image", reference_requirements="product reference optional",
         source="synthetic", model="gpt-image-2",
         original_prompt="A breakout product hero advertisement. A premium skincare bottle breaking through the frame with forced perspective and foreground overlap. Particles and droplets around it. Commercial lighting with rim highlights. Preserve the bottle geometry and label exactly. Controlled negative space, luxury commercial style.",
         visual_intent="A breakout product hero.",
         subject="skincare bottle", environment="clean gradient",
         composition="breakout + forced perspective", lighting="commercial rim",
         camera="three-quarter", lens="n/a", perspective="slight low angle",
         style="luxury commercial", color="product + neutral + accent",
         materials="glass, liquid", typography="label text",
         layout="centered breakout",
         supporting_elements=["particles", "droplets"],
         techniques=["product preservation", "subject hierarchy", "lighting control"],
         constraints=["preserve geometry", "protect label"],
         negative_constraints=["no clutter"],
         tags=["product", "hero", "breakout", "commercial"],
         pattern_ids=["pattern-breakout-product-hero"],
         style_ids=["style-luxury-commercial"],
         technique_ids=["technique-product-preservation", "technique-subject-hierarchy", "technique-lighting-control"],
         recipe_ids=["recipe-product-hero-ad"]),
    Case(id="case-editorial-poster", title="编辑风海报",
         category="poster", use_case="marketing",
         user_intent="An editorial text-first poster.",
         input_type="text-to-image", reference_requirements="none",
         source="synthetic", model="gpt-image-2",
         original_prompt="An editorial text-first poster. Headline \"DESIGN IS INTELLIGENCE MADE VISIBLE\" in bold Swiss sans-serif. Supporting text in smaller refined type. A minimal geometric illustration. Swiss editorial style, high contrast black and white with one accent. Generous margins, text readability first.",
         visual_intent="A Swiss editorial poster.",
         subject="headline", environment="clean background",
         composition="text-first", lighting="even",
         camera="n/a", lens="n/a", perspective="flat",
         style="Swiss editorial", color="black + white + accent",
         materials="paper", typography="bold Swiss sans-serif",
         layout="headline + text + illustration",
         supporting_elements=["geometric illustration"],
         techniques=["text rendering", "visual hierarchy", "whitespace"],
         constraints=["text readability first"],
         negative_constraints=["no clutter"],
         tags=["poster", "editorial", "swiss"],
         pattern_ids=["pattern-editorial-text-first-poster"],
         style_ids=["style-editorial-minimalism"],
         technique_ids=["technique-text-rendering", "technique-visual-hierarchy", "technique-whitespace"],
         recipe_ids=["recipe-editorial-poster"]),
]

# --------------------------------------------------------------------------- prompts

PROMPTS = [
    Prompt(id="prompt-luxury-product-template", title="Luxury product on dark water (template)",
           original_prompt="Product: [BRAND] [PRODUCT NAME] - [bottle shape], [label description], [liquid color]. Scene: Luxury product shot floating on dark water with [flower type] in [colors] arranged around it. [Lighting style] creates reflections and ripples across the water. Mood & Style: ethereal and luxurious, high-end commercial photography, [camera angle], shallow depth of field with soft bokeh background.",
           source_repo="awesome-nanobanana-pro", source_url="https://github.com/ZeroLu/awesome-nanobanana-pro",
           author="AmirMušić", license="CC BY 4.0", target_model="nano-banana-pro",
           category="product advertisement", tags=["luxury", "template", "product"],
           why_it_is_good="A parameterized luxury product template with named variables.",
           techniques_used=["templated variables", "lighting control"],
           visual_pattern="Centered Luxury Product Shot", style="luxury commercial",
           prompt_dna="Luxury Product Shot DNA", tier="annotated"),
    Prompt(id="prompt-double-exposure", title="Double-exposure fashion portrait",
           original_prompt="A cinematic double-exposure fashion portrait featuring a woman with the uploaded face used 100% as reference, wearing stylish metallic aviator sunglasses. The composition blends a large semi-transparent close-up profile of her face on the left with her full-body figure on the right. Minimalist neutral studio setting. Warm desaturated sepia and charcoal palette, soft golden-orange light-leak flare. Professional 85mm lens, high-contrast soft cinematic lighting, natural skin texture, luxury fashion-editorial aesthetic.",
           source_repo="freestylefly-awesome-gpt-image-2", source_url="https://github.com/freestylefly/awesome-gpt-image-2",
           author="@Anaya_Ai12", license="MIT", target_model="gpt-image-2",
           category="photography", tags=["portrait", "double-exposure", "fashion"],
           why_it_is_good="Combines reference-image technique with a strong compositional device.",
           techniques_used=["reference image", "camera & lens control", "color grading"],
           visual_pattern="Double-exposure Portrait", style="cinematic realism",
           prompt_dna="Cinematic Portrait DNA", tier="annotated"),
    Prompt(id="prompt-product-box-dieline", title="3D product box from dieline",
           original_prompt="Assemble the dieline into a flawless 3D box with accurate panels, clean folds, undistorted type, and artwork preserved exactly. Shoot it upright at a refined three-quarter angle in a minimal premium studio setting with a soft neutral background, diffused light, subtle shadows, no props, true colours, matte paperboard texture. The box front reads \"AURAE / COLD-BREW MATCHA / 12 fl oz\" in clean sans-serif. Side panel shows small ingredient list in 8pt type.",
           source_repo="gpt-image2-skill", source_url="https://github.com/wuyoscar/GPT-Image2-Skill",
           author="wuyoscar", license="MIT", target_model="gpt-image-2",
           category="product advertisement", tags=["product", "packaging", "3d"],
           why_it_is_good="Product preservation + text rendering in one production prompt.",
           techniques_used=["product preservation", "text rendering", "lighting control"],
           visual_pattern="Floating 3D Product Scene", style="3D commercial",
           prompt_dna="Breakout Product Hero DNA", tier="annotated"),
]

# --------------------------------------------------------------------------- write


def main() -> None:
    store = KnowledgeStore("data")
    store.save("source", SOURCES)
    store.save("model", MODELS)
    store.save("style", STYLES)
    store.save("technique", TECHNIQUES)
    store.save("pattern", PATTERNS)
    store.save("recipe", RECIPES)
    store.save("dna", DNA)
    store.save("case", CASES)
    store.save("prompt", PROMPTS)
    print("seeded:", store.stats())


if __name__ == "__main__":
    main()
